# **Task 2: SQL for Data Extraction and Analysis**

### **Objective**

The objective of this task is to use SQL queries for extracting business insights from the cleaned dataset. SQLite is integrated with Python using SQLAlchemy.

#### **Tools Used**

- Python
- Pandas
- SQLAlchemy
- SQLite
- Jupyter Notebook

In [106]:
import pandas as pd 
from sqlalchemy import create_engine

---

##### **Loading the Cleaned Dataset**
The cleaned dataset from Task 1 is loaded into Pandas.

In [107]:
df=pd.read_csv("../data/cleaned_superstore.csv")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656

---

##### **Creating SQLite Database**

The cleaned dataset is stored inside a SQLite database table.

In [108]:
engine=create_engine("sqlite:///sales.db")
df.to_sql(
    "sales",
    engine,
    if_exists="replace",
    index=False
)

8827

---

## **SQL Fundamentals**

Basic SQL operations are performed to understand data retrieval and analysis

#### **Practice SELECT**

##### **SELECT Statement**
Retrieve records from the sales table

In [109]:
pd.read_sql("""
            SELECT *
            FROM sales
            LIMIT 5
            """,engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656

##### **Observation**

The query successfully retrieves the first five records from the database table.

---

#### **Practice WHERE**

##### **WHERE Clause**
Filter records based on conditions.

In [110]:
pd.read_sql("""
            SELECT [Customer Name]
            FROM sales
            WHERE Sales>50
            """,engine)

        Customer Name
0         Claire Gute
1     Brosina Hoffman
2        Irene Maddox
3       Harold Pawlan
4     Alejandro Grove
...               ...
3970     Ruben Ausman
3971     Ruben Ausman
3972      Dave Brooks
3973      Dave Brooks
3974     Chris Cortes

[3975 rows x 1 columns]

##### **Observation**

The query retrieves the Customer Name whose sales are greater than 50

---

#### **Practice ORDER BY**

##### **ORDER BY Clause**
Sort records in descending order of sales.

In [111]:
pd.read_sql(""" 
            SELECT *
            FROM sales
            ORDER BY Sales DESC
            LIMIT 10
            """,engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,5220,CA-2017-145653,2017-09-01,2017-09-01,Same Day,CA-12775,Cynthia Arntzen,Consumer,United States,Detroit,...,48205,Central,FUR-CH-10004875,Furniture,Chairs,Harbour Creations 67200 Series Stacking Chairs,498.260,7,0.0,134.5302
1,8339,CA-2014-153087,2014-12-27,2015-01-03,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Decatur,...,35601,South,TEC-AC-10003198,Technology,Accessories,Enermax Acrylux Wireless Keyboard,498.000,5,0.0,184.2600
2,7558,CA-2017-159506,2017-11-27,2017-12-02,Standard Class,JR-16210,Justin Ritter,Corporate,United States,Columbus,...,47201,Central,OFF-BI-10004519,Office Supplies,Binders,GBC DocuBind P100 Manual Binding Machine,497.940,3,0.0,224.0730
3,1775,CA-2014-118976,2014-04-28,2014-05-03,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Baltimore,...,21215,East,OFF-ST-10000877,Office Supplies,Storage,Recycled Steel Personal File for Standard File...,497.610,9,0.0,129.3786
4,8533,CA-2016-156748,2016-11-30,2016-12-06,Standard Class,BS-11755,Bruce Stewart,Consumer,United States,Detroit,...,48227,Central,OFF-ST-10001370,Office Supplies,Storage,Sensible Storage WireTech Storage Systems,496.860,7,0.0,24.8430
5,2242,US-2016-126893,2016-11-26,2016-12-01,Standard Class,CT-11995,Carol Triggs,Consumer,United States,Philadelphia,...,19134,East,TEC-PH-10004165,Technology,Phones,Mitel MiVoice 5330e IP Phone,494.982,3,0.4,-115.4958
6,6854,US-2017-162670,2017-12-23,2017-12-28,Second Class,MF-18250,Monica Federle,Corporate,United States,Little Rock,...,72209,South,TEC-PH-10003601,Technology,Phones,Ativa D5772 2-Line 5.8GHz Digital Expandable C...,494.970,3,0.0,148.4910
7,8899,CA-2015-163237,2015-08-07,2015-08-09,Second Class,EM-14095,Eudokia Martin,Corporate,United States,Springfield,...,22153,South,TEC-PH-10003601,Technology,Phones,Ativa D5772 2-Line 5.8GHz Digital Expandable C...,494.970,3,0.0,148.4910
8,601,US-2016-100720,2016-07-16,2016-07-21,Standard Class,CK-12205,Chloris Kastensmidt,Consumer,United States,Philadelphia,...,19120,East,TEC-PH-10003963,Technology,Phones,GE 2-Jack Phone Line Splitter,494.376,4,0.4,-115.3544
9,3288,CA-2015-157770,2015-12-13,2015-12-15,First Class,RD-19585,Rob Dowd,Consumer,United States,Temecula,...,92592,West,TEC-PH-10001530,Technology,Phones,Plantronics Voyager Pro Legend,494.376,3,0.2,49.4376

##### **Observation**

Retrieves the records which are sorted in descending order.

---

#### **Practice LIMIT**

In [112]:
pd.read_sql("""
            SELECT *
            FROM sales
            LIMIT 10
            """,engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656
5,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825
6,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.900,5,0.0,34.4700
7,13,CA-2017-114412,2017-04-15,2017-04-20,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,...,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3,0.2,5.4432
8,14,CA-2016-161389,2016-12-05,2016-12-10,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,...,98103,West,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.976,3,0.2,132.5922
9,15,US-2015-118983,2015-11-22,2015-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.810,5,0.8,-123.8580

##### **Observation**

Retrieves 10 records from the database

---

#### **Practice GROUP BY**

In [113]:
pd.read_sql(""" 
            SELECT Category,
            SUM(Sales) AS TotalSales
            FROM sales
            GROUP BY Category
            """,engine)

          Category   TotalSales
0        Furniture  247877.6984
1  Office Supplies  343425.0040
2       Technology  228415.3530

##### **Observation**

The GROUP BY clause groups records based on category and calculates total sales for each category. This helps compare category-wise performance.

---

#### **Practice HAVING**

In [114]:
pd.read_sql(""" 
            SELECT Category,
            SUM(Sales) AS TotalSales
            FROM sales
            GROUP BY Category
            HAVING TotalSales > 300000
            """,engine)

          Category  TotalSales
0  Office Supplies  343425.004

### Observation

The HAVING clause filters grouped data after aggregation. It displays only categories that satisfy the specified sales threshold.

---

## **Advanced SQL Section**

### **Advanced SQL Concepts**

#### **Practice SubQuery**

In [115]:
pd.read_sql(""" 
            SELECT *
            FROM sales
            WHERE Sales>
            (
                SELECT AVG(Sales)
                FROM sales
            )
            """,engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.900,5,0.0,34.4700
2,14,CA-2016-161389,2016-12-05,2016-12-10,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,...,98103,West,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.976,3,0.2,132.5922
3,20,CA-2014-143336,2014-08-27,2014-09-01,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,94109,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.480,3,0.2,16.0110
4,30,US-2015-150630,2015-09-17,2015-09-21,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,FUR-FU-10004848,Furniture,Furnishings,"Howard Miller 13-3/4"" Diameter Brushed Chrome ...",124.200,3,0.2,15.5250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2753,9980,US-2016-103674,2016-12-06,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.472,14,0.2,153.1152
2754,9984,US-2016-157728,2016-09-22,2016-09-28,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,49505,Central,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.980,2,0.0,27.4344
2755,9989,CA-2017-163629,2017-11-17,2017-11-21,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.100,5,0.0,55.6470
2756,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
2757,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

##### **Observation**

The subquery calculates the average sales value, and the outer query displays records with sales above the average. This helps identify high-performing transactions.

---

#### **Practice CTE**

In [116]:
pd.read_sql("""
            WITH Category_sales AS
            (
                SELECT Category,
                SUM(Sales) AS TotalSales
                FROM sales
                GROUP BY Category
            )
            SELECT *
            FROM Category_sales
            """,engine)

          Category   TotalSales
0        Furniture  247877.6984
1  Office Supplies  343425.0040
2       Technology  228415.3530

##### **Observation**

The Common Table Expression (CTE) improves query readability by creating a temporary result set that can be referenced later.

---

#### **Practice ROW_NUMBER**

In [117]:
pd.read_sql(""" 
            SELECT [Product Name],
            Sales,
            ROW_NUMBER() OVER
            (ORDER BY Sales DESC) AS Rowno
            FROM sales
            LIMIT 20
            """,engine)

                                         Product Name    Sales  Rowno
0      Harbour Creations 67200 Series Stacking Chairs  498.260      1
1                   Enermax Acrylux Wireless Keyboard  498.000      2
2            GBC DocuBind P100 Manual Binding Machine  497.940      3
3   Recycled Steel Personal File for Standard File...  497.610      4
4           Sensible Storage WireTech Storage Systems  496.860      5
5                        Mitel MiVoice 5330e IP Phone  494.982      6
6   Ativa D5772 2-Line 5.8GHz Digital Expandable C...  494.970      7
7   Ativa D5772 2-Line 5.8GHz Digital Expandable C...  494.970      8
8                       GE 2-Jack Phone Line Splitter  494.376      9
9                      Plantronics Voyager Pro Legend  494.376     10
10  Barricks 18" x 48" Non-Folding Utility Table w...  493.920     11
11  Bush Heritage Pine Collection 5-Shelf Bookcase...  493.430     12
12                           Hon Olson Stacker Stools  492.835     13
13   Nortel Meridian M3904 Professional Digital phone  492.768     14
14  Dot Matrix Printer Tape Reel Labels, White, 50...  491.550     15
15  Dot Matrix Printer Tape Reel Labels, White, 50...  491.550     16
16          Belkin 5 Outlet SurgeMaster Power Centers  490.320     17
17                SAFCO Commercial Wire Shelving, 72h  489.920     18
18  SAFCO PlanMaster Heigh-Adjustable Drafting Tab...  489.230     19
19                    Global Ergonomic Managers Chair  488.646     20

##### **Observation**

ROW_NUMBER assigns a unique sequential number to each row based on sales ranking. It is useful for ranking and reporting purposes.

---

#### **Practice RANK**

In [118]:
pd.read_sql(""" 
            SELECT [Product Name],
            Sales,
            RANK() OVER 
            (ORDER BY Sales DESC) AS Rankno
            FROM sales
            LIMIT 20
            """,engine)

                                         Product Name    Sales  Rankno
0      Harbour Creations 67200 Series Stacking Chairs  498.260       1
1                   Enermax Acrylux Wireless Keyboard  498.000       2
2            GBC DocuBind P100 Manual Binding Machine  497.940       3
3   Recycled Steel Personal File for Standard File...  497.610       4
4           Sensible Storage WireTech Storage Systems  496.860       5
5                        Mitel MiVoice 5330e IP Phone  494.982       6
6   Ativa D5772 2-Line 5.8GHz Digital Expandable C...  494.970       7
7   Ativa D5772 2-Line 5.8GHz Digital Expandable C...  494.970       7
8                       GE 2-Jack Phone Line Splitter  494.376       9
9                      Plantronics Voyager Pro Legend  494.376       9
10  Barricks 18" x 48" Non-Folding Utility Table w...  493.920      11
11  Bush Heritage Pine Collection 5-Shelf Bookcase...  493.430      12
12                           Hon Olson Stacker Stools  492.835      13
13   Nortel Meridian M3904 Professional Digital phone  492.768      14
14  Dot Matrix Printer Tape Reel Labels, White, 50...  491.550      15
15  Dot Matrix Printer Tape Reel Labels, White, 50...  491.550      15
16          Belkin 5 Outlet SurgeMaster Power Centers  490.320      17
17                SAFCO Commercial Wire Shelving, 72h  489.920      18
18  SAFCO PlanMaster Heigh-Adjustable Drafting Tab...  489.230      19
19                    Global Ergonomic Managers Chair  488.646      20

##### **Observation**

RANK assigns positions based on sales values. Products with equal sales receive the same rank.

---

#### **Practice LAG**

In [119]:
pd.read_sql(""" 
            SELECT [Order Date],
            Sales,
            LAG(Sales,1) OVER
            (ORDER BY [Order Date]) AS PreviousSales
            FROM sales
            LIMIT 20
            """,engine)

    Order Date    Sales  PreviousSales
0   2014-01-03   16.448            NaN
1   2014-01-04   11.784         16.448
2   2014-01-04  272.736         11.784
3   2014-01-04    3.540        272.736
4   2014-01-05   19.536          3.540
5   2014-01-06   19.440         19.536
6   2014-01-06   12.780         19.440
7   2014-01-06    5.480         12.780
8   2014-01-06  391.980          5.480
9   2014-01-06   31.120        391.980
10  2014-01-06    6.540         31.120
11  2014-01-07   76.728          6.540
12  2014-01-07   10.430         76.728
13  2014-01-09    9.344         10.430
14  2014-01-09   31.200          9.344
15  2014-01-10    2.890         31.200
16  2014-01-10   51.940          2.890
17  2014-01-11    9.940         51.940
18  2014-01-13   11.360          9.940
19  2014-01-13   50.940         11.360

##### **Observation**

LAG retrieves the previous row's sales value, enabling comparison between consecutive transactions.

---

#### **Practice LEAD**

In [120]:
pd.read_sql(""" 
            SELECT [Order Date],
            Sales,
            LEAD(Sales,1) OVER
            (ORDER BY [Order Date]) AS NextSales
            FROM sales
            LIMIT 20
            """,engine)

    Order Date    Sales  NextSales
0   2014-01-03   16.448     11.784
1   2014-01-04   11.784    272.736
2   2014-01-04  272.736      3.540
3   2014-01-04    3.540     19.536
4   2014-01-05   19.536     19.440
5   2014-01-06   19.440     12.780
6   2014-01-06   12.780      5.480
7   2014-01-06    5.480    391.980
8   2014-01-06  391.980     31.120
9   2014-01-06   31.120      6.540
10  2014-01-06    6.540     76.728
11  2014-01-07   76.728     10.430
12  2014-01-07   10.430      9.344
13  2014-01-09    9.344     31.200
14  2014-01-09   31.200      2.890
15  2014-01-10    2.890     51.940
16  2014-01-10   51.940      9.940
17  2014-01-11    9.940     11.360
18  2014-01-13   11.360     50.940
19  2014-01-13   50.940      5.640

##### **Observation**

LEAD retrieves the next row's sales value, making it easier to compare current and future records.

---

#### **Create View**

In [121]:
with engine.connect() as conn:
    conn.exec_driver_sql("DROP VIEW IF EXISTS TopSales")

In [122]:
with engine.connect() as conn:
    conn.exec_driver_sql(""" 
    CREATE VIEW TopSales AS
    SELECT *
    FROM sales
    WHERE Sales > 10
""")

In [123]:
pd.read_sql(""" 
            SELECT *
            FROM TopSales
            LIMIT 5
            """,engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825

##### **Observation**

The view was created successfully and stores frequently used query results. It simplifies access to high-value sales records without repeatedly writing the same SQL query.

---

# **BUSINESS QUESTIONS SECTION**

#### **1) Rank Products Based on Sales Performance**

In [124]:
pd.read_sql(""" 
            SELECT [Product Name],
            Sales,
            RANK() OVER (ORDER BY Sales DESC) AS
            ProductRank
            FROM sales
            LIMIT 20
            """,engine)

                                         Product Name    Sales  ProductRank
0      Harbour Creations 67200 Series Stacking Chairs  498.260            1
1                   Enermax Acrylux Wireless Keyboard  498.000            2
2            GBC DocuBind P100 Manual Binding Machine  497.940            3
3   Recycled Steel Personal File for Standard File...  497.610            4
4           Sensible Storage WireTech Storage Systems  496.860            5
5                        Mitel MiVoice 5330e IP Phone  494.982            6
6   Ativa D5772 2-Line 5.8GHz Digital Expandable C...  494.970            7
7   Ativa D5772 2-Line 5.8GHz Digital Expandable C...  494.970            7
8                       GE 2-Jack Phone Line Splitter  494.376            9
9                      Plantronics Voyager Pro Legend  494.376            9
10  Barricks 18" x 48" Non-Folding Utility Table w...  493.920           11
11  Bush Heritage Pine Collection 5-Shelf Bookcase...  493.430           12
12                           Hon Olson Stacker Stools  492.835           13
13   Nortel Meridian M3904 Professional Digital phone  492.768           14
14  Dot Matrix Printer Tape Reel Labels, White, 50...  491.550           15
15  Dot Matrix Printer Tape Reel Labels, White, 50...  491.550           15
16          Belkin 5 Outlet SurgeMaster Power Centers  490.320           17
17                SAFCO Commercial Wire Shelving, 72h  489.920           18
18  SAFCO PlanMaster Heigh-Adjustable Drafting Tab...  489.230           19
19                    Global Ergonomic Managers Chair  488.646           20

##### **Insight**

Ranking products helps identify best-performing items and supports business decision-making

---

#### **2) What are the Top 5 Products by Sales?**

In [125]:
pd.read_sql(""" 
            SELECT [Product Name],
            SUM(Sales) AS TotalSales
            FROM sales
            GROUP BY [Product Name]
            ORDER BY TotalSales DESC
            LIMIT 5
            """,engine)

                                       Product Name  TotalSales
0                        KI Adjustable-Height Table    4036.761
1   Global Wood Trimmed Manager's Task Chair, Khaki    3621.004
2        Situations Contoured Folding Chairs, 4/Set    2959.866
3         Global High-Back Leather Tilter, Burgundy    2841.069
4  Nortel Meridian M3904 Professional Digital phone    2802.618

##### **Insight**

The top 5 products contribute a significant portion of total revenue. These products should be prioritized for inventory management and promotional campaigns.

---

#### **3) Which Product Category Generates the Highest Revenue?**

In [126]:
pd.read_sql(""" 
            SELECT Category,
            SUM(Sales) AS TotalSales
            FROM sales
            GROUP BY Category
            ORDER BY TotalSales DESC
            """,engine)

          Category   TotalSales
0  Office Supplies  343425.0040
1        Furniture  247877.6984
2       Technology  228415.3530

##### **Insight**

The category with the highest revenue contributes most to the company's sales performance and should receive continued investment.

---

#### **4) Which Region has the Highest Salary?**

In [127]:
pd.read_sql(""" 
            SELECT Region,
            SUM(Sales) AS TotalSales
            FROM sales
            GROUP BY Region
            ORDER BY TotalSales DESC
            """,engine)

    Region   TotalSales
0     West  275810.2625
1     East  232887.4840
2  Central  183440.9134
3    South  127579.3955

##### **Insight**

The highest-performing region can serve as a benchmark for improving sales strategies in other regions.

---

#### **5) Who are the top 10 Customers by Sales?**

In [128]:
pd.read_sql(""" 
            SELECT [Customer Name],
            SUM(Sales) AS TotalSales
            FROM sales
            GROUP BY [Customer Name]
            ORDER BY TotalSales DESC
            LIMIT 10
            """,engine)

     Customer Name  TotalSales
0       Paul Prost   4196.9280
1  Laura Armstrong   3751.7980
2     Ken Lonsdale   3371.6910
3         John Lee   3338.3520
4    William Brown   3131.9740
5     Noel Staavos   2964.8230
6      Rick Wilson   2879.8910
7    Sally Hughsby   2865.5995
8     Edward Hooks   2821.2100
9    Arthur Gainer   2806.8510

##### **Insight**

A small number of customers contribute heavily to revenue, highlighting the importance of customers retention.

---

#### **6) What is the monthly sales trend?**

In [129]:
pd.read_sql(""" 
            SELECT strftime('%Y-%m',[Order Date]) AS
            Month,
            SUM(Sales) AS TotalSales
            FROM sales
            GROUP BY Month
            ORDER BY Month
            """,engine)

      Month  TotalSales
0   2014-01   5438.1550
1   2014-02   3263.6720
2   2014-03  12452.5360
3   2014-04  11421.1910
4   2014-05  10456.7150
5   2014-06  10510.3486
6   2014-07  11024.2770
7   2014-08  12954.6225
8   2014-09  20696.5088
9   2014-10  13696.0970
10  2014-11  22934.5397
11  2014-12  23771.2075
12  2015-01   5594.0340
13  2015-02   5063.5290
14  2015-03  10771.9416
15  2015-04  13167.9905
16  2015-05  10807.4140
17  2015-06  10842.2570
18  2015-07  13015.7570
19  2015-08  12552.8122
20  2015-09  20435.1800
21  2015-10  15397.4880
22  2015-11  27483.3603
23  2015-12  27471.5480
24  2016-01   8508.9570
25  2016-02   9152.2500
26  2016-03  15162.3320
27  2016-04  12776.6920
28  2016-05  16370.4500
29  2016-06  18361.5700
30  2016-07  16262.3720
31  2016-08  13239.3678
32  2016-09  28732.5435
33  2016-10  15377.2050
34  2016-11  30624.2540
35  2016-12  31389.2940
36  2017-01  12369.8630
37  2017-02  10470.4194
38  2017-03  21964.4808
39  2017-04  15790.3786
40  2017-05  20387.3354
41  2017-06  21350.8592
42  2017-07  20725.4830
43  2017-08  17624.2220
44  2017-09  37662.6420
45  2017-10  21863.2602
46  2017-11  36791.9560
47  2017-12  35536.6868

##### **Insight**

Monthly trends help identify seasonal patterns and support future sales forecasting.

---

#### **7) Which Products Generate the Highest Profit?**

In [130]:
pd.read_sql(""" 
            SELECT [Product Name],
            SUM(Profit) AS TotalProfit
            FROM sales
            GROUP BY [Product Name]
            ORDER BY TotalProfit DESC
            LIMIT 10
            """,engine)

                                        Product Name  TotalProfit
0                                  Easy-staple paper    1096.0292
1  Dot Matrix Printer Tape Reel Labels, White, 50...     904.4520
2                                         Xerox 1908     799.3944
3                                         Xerox 1945     756.2655
4                                    Staple envelope     751.6290
5                                          Xerox 189     746.5320
6                                         Xerox 1919     729.6220
7                       Enermax Aurora Lite Keyboard     722.1060
8                   Logitech Gaming G510s - Keyboard     676.5204
9  GE 48" Fluorescent Tube, Cool White Energy Sav...     664.8410

##### **Insight**

High-Profit products should receive additional marketing attention because they contribute significantly to business growth.

---

#### **8) Which Products generate the lowest Profit?**

In [131]:
pd.read_sql(""" 
            SELECT [Product Name],
            SUM(Profit) AS TotalProfit
            FROM sales
            GROUP BY [Product Name]
            ORDER BY TotalProfit ASC
            LIMIT 10
            """,engine)

                                        Product Name  TotalProfit
0  3.6 Cubic Foot Counter Height Office Refrigerator   -1378.8216
1                Ibico Hi-Tech Manual Binding System   -1372.4550
2                Hoover Upright Vacuum With Dirt Cup   -1181.2824
3       GBC ProClick 150 Presentation Binding System   -1143.8476
4         O'Sullivan 4-Shelf Bookcase in Odessa Pine   -1006.5536
5           Tenex Chairmat w/ Average Lip, 45" x 53"    -681.1200
6                Okidata MB491 Multifunction Printer    -643.7100
7    StarTech.com 10/100 VDSL2 Ethernet Extender Kit    -639.2640
8                            Bestar Classic Bookcase    -612.9387
9                Bevis Rectangular Conference Tables    -586.8396

##### **Insight**

Products with low or negative profits should be reviewed for pricing, discounts, or operational inefficiencies.

---

#### **9) Which Customer Segment Contributes the most sales?**

In [132]:
pd.read_sql(""" 
            SELECT Segment,
            SUM(Sales) AS TotalSales
            FROM sales
            GROUP BY Segment
            ORDER BY TotalSales DESC
            """,engine)

       Segment   TotalSales
0     Consumer  437711.0838
1    Corporate  240011.9418
2  Home Office  141995.0298

##### **Insight**

The most valuable customer segment should be the primary focus for future marketing strategies.

---

#### **10) What is the Average sales value by Category?**

In [133]:
pd.read_sql(""" 
            SELECT Category,
            AVG(Sales) AS AverageSales
            FROM sales
            GROUP BY Category
            """,engine)

          Category  AverageSales
0        Furniture    149.865598
1  Office Supplies     59.976424
2       Technology    157.854425

##### **Insight**

Average sales values help understand customer spending behavior across different product categories.

---

# **Final Conclusion**

## **Summary of Analysis**

SQL was used to extract meaningful business insights from the Superstore dataset stored in a SQLite database.

### **Key Findings**

1. A small number of products generated a large percentage of total sales.
2. Certain categories consistently outperformed others in revenue generation.
3. Regional sales analysis revealed significant performance differences.
4. Customer spending patterns highlighted the importance of retaining top customers.
5. Sales trends indicated seasonal variations across different periods.
6. High-profit products contributed substantially to overall profitability.
7. Some products generated low profits and require business review.
8. Customer segments showed varying levels of contribution to revenue.
9. Average sales values differed across categories.
10. Product ranking provided a clear picture of sales performance.

## **Outcome**

The integration of SQL and Python enabled efficient data extraction, business analysis, and decision-making. This task strengthened practical SQL skills including filtering, aggregation, subqueries, window functions, views, and business analytics.